In [2]:
#Broadcasting

#Automatic alignment of an array.

In [3]:
import numpy as np

In [4]:
n1 = np.array([1,2,3])

scalar = 10

result = n1 + scalar

print("Broadcasted result : ",result)

Broadcasted result :  [11 12 13]


In [6]:
#Add two array using broadcasting

n1 = np.array([[1,2,3],[5,8,9]])
n2 = np.array([45,6,7])

result = n1 + n2

print("Broadcasted result : ",result)

Broadcasted result :  [[46  8 10]
 [50 14 16]]


In [15]:
#Random sampling with numpy..

#Random sampling is the process of generating random numbers with specified distribution like random sampling from arrays.
#It is majorily used in statistical analysis and simulation.

sample_float = np.random.rand(5) #float number between 0 to 1.
print("Random samples : ",sample_float)

sample_float_2d = np.random.rand(3,3) #random 2d array for size (3X3).
print("Random float 2d array : ",sample_float_2d)

sample_int = np.random.randint(1,10) #integer number between 1 to 10.
print("Random int array : ",sample_int)

sample_int_size = np.random.randint(1,10,size = 5) # five integer number between 1 to 10.
print("Five Random int array  : ",sample_int_size)

sample_int_2d = np.random.randint(1,10,size = (3,3)) # (3X3) integer aaray number between 1 to 10.
print("2d Random int array  : ",sample_int_2d)


Random samples :  [0.64887508 0.50772587 0.41230662 0.3593918  0.72519349]
Random float 2d array :  [[0.45443343 0.88038775 0.22749821]
 [0.06270726 0.28423559 0.9147584 ]
 [0.02565917 0.60190354 0.29111525]]
Random int array :  9
Five Random int array  :  [7 5 4 3 4]
2d Random int array  :  [[2 7 9]
 [7 4 9]
 [5 1 4]]


In [20]:
#Generate random samples from a normal distribution
mean = 0
std_dev = 1
normal_samples = np.random.normal(mean,std_dev,5)

#Print the generated samples
print("Normal distribution samples : ")
print(normal_samples)

Normal distribution samples : 
[ 0.11786103  0.25368061  0.47074015 -1.27876562  0.8874617 ]


In [30]:
#Example of random sampling for data augmentation

data = np.array([[1,2],[3,4],[5,6]])

print("Normal data : ")
print(data)
#Random shuffle the rows
np.random.shuffle(data)

#Print the shuffled data
print("Shuffled data : ")
print(data)

Normal data : 
[[1 2]
 [3 4]
 [5 6]]
Shuffled data : 
[[3 4]
 [1 2]
 [5 6]]


In [31]:
#Vectorization in numpy..

#It is the process of improving performance with vectorized operations.
#It avoids loops for enhanced speed because loops can cause memory mismanagement.
#It benchmarks numpy performance against pure python code.

In [33]:
#Traditional approach without vectorization
def add_arrays(arr1,arr2):
    result=[]
    for i in range(len(arr1)):
        result.append(arr1[i]+arr2[i])
    return result

#Vectorized approch using NumPy
def add_arrays_vectorized(arr1,arr2):
    return np.add(arr1,arr2)

arr1 = [1,2,3,4]
arr2 = [5,6,78,8]

print("Normal : ",add_arrays(arr1,arr2))
print("Vectorized : ",add_arrays_vectorized(arr1,arr2))

Normal :  [6, 8, 81, 12]
Vectorized :  [ 6  8 81 12]


In [36]:
#Genrate two arrays for demonstration

arr1 = np.random.rand(100000)
arr2 = np.random.rand(100000)

#Time traditional approach
traditional_time = %timeit -o add_arrays(arr1,arr2)

#Time vectorized approch
vectorized_time = %timeit -o add_arrays_vectorized(arr1,arr2)

print("Traditional Approch Time : ",traditional_time)
print("Vectorized Approch Time : ",vectorized_time)

51.1 ms ± 1.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
103 μs ± 1.62 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
Traditional Approch Time :  51.1 ms ± 1.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
Vectorized Approch Time :  103 μs ± 1.62 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
